version: "2"
services:
  web:
    build: ./coffee
    ports:
      - "5000:5000"
    volumes:
      - ./coffee:/code
    depends_on:
      - bean
      - report
  bean:
    image: bean_web
    build: ./bean
    ports:
      - "4000:4000"
    volumes:
      - ./bean:/code
  report:
    image: report_web
    build: ./report
    ports:
      - "5001:5000"
    volumes:
      - ./report:/code